import { Injectable } from '@angular/core';
import { Observable } from "rxjs";

@Injectable()
export class MockDataService {

    private mockList: any = {
        "odata.metadata": "https://bluesidenl.sharepoint.com/sites/dev/dashboard/_api/$metadata#SP.ListData.TestlistListItems",
        "value": [
            {
            "odata.type": "SP.Data.TestlistListItem",
            "odata.id": "b9ce2957-d2af-4bf4-8d25-649a1b5a441f",
            "odata.etag": "\"5\"",
            "odata.editLink": "Web/Lists(guid'3f891819-5635-47ff-81c1-992754c7859d')/Items(6008)",
            "FileSystemObjectType": 0,
            "Id": 6008,
            "ServerRedirectedEmbedUri": null,
            "ServerRedirectedEmbedUrl": "",
            "Title": "Test Entry",
            "Text": null,
            "Integer": 8,
            "ContentTypeId": "0x01008DBF3136F91A674284F05535CB9FAB51",
            "ComplianceAssetId": null,
            "Note": null,
            "Datetime": null,
            "Choice": "Choice 1",
            "MultiChoice": [
                "Choice 1"
            ],
            "Boolean": true,
            "Number": 33,
            "Currency": null,
            "URL": null,
            "UserId": null,
            "UserStringId": null,
            "MultiPersonId": null,
            "MultiPersonStringId": null,
            "AverageRating": null,
            "RatingCount": null,
            "RatedByStringId": null,
            "LikesCount": null,
            "LikedByStringId": null,
            "Site_x0020_URL": null,
            "Site_x0020_title": null,
            "ID": 6008,
            "Modified": "2017-12-13T17:52:01Z",
            "Created": "2017-11-22T15:33:43Z",
            "AuthorId": 9,
            "EditorId": 9,
            "OData__UIVersionString": "1.0",
            "Attachments": false,
            "GUID": "a3919b18-de59-4aed-a4b3-adce41ee2b6d"
        },
            {
            "odata.type": "SP.Data.TestlistListItem",
            "odata.id": "2d9bca33-d9c9-43f4-95d6-af37914662cc",
            "odata.etag": "\"22\"",
            "odata.editLink": "Web/Lists(guid'3f891819-5635-47ff-81c1-992754c7859d')/Items(6023)",
            "FileSystemObjectType": 0,
            "Id": 6023,
            "ServerRedirectedEmbedUri": null,
            "ServerRedirectedEmbedUrl": "",
            "Title": "Subsite test",
            "Text": null,
            "Integer": 90,
            "ContentTypeId": "0x01008DBF3136F91A674284F05535CB9FAB51",
            "ComplianceAssetId": null,
            "Note": null,
            "Datetime": null,
            "Choice": "Choice 1",
            "MultiChoice": null,
            "Boolean": true,
            "Number": 70,
            "Currency": null,
            "URL": null,
            "UserId": null,
            "UserStringId": null,
            "MultiPersonId": null,
            "MultiPersonStringId": null,
            "AverageRating": null,
            "RatingCount": null,
            "RatedByStringId": null,
            "LikesCount": null,
            "LikedByStringId": null,
            "Site_x0020_URL": "https://bluesidenl.sharepoint.com/sites/dev/dashboard/subsite-test/",
            "Site_x0020_title": null,
            "ID": 6023,
            "Modified": "2017-12-13T17:51:34Z",
            "Created": "2017-11-24T09:09:11Z",
            "AuthorId": 9,
            "EditorId": 9,
            "OData__UIVersionString": "1.0",
            "Attachments": false,
            "GUID": "c3b9e8c0-bac3-490f-b756-3df3dbab50a9"
        },
            {
            "odata.type": "SP.Data.TestlistListItem",
            "odata.id": "e1c4302a-a527-4bae-8250-65df9364ed59",
            "odata.etag": "\"13\"",
            "odata.editLink": "Web/Lists(guid'3f891819-5635-47ff-81c1-992754c7859d')/Items(6024)",
            "FileSystemObjectType": 0,
            "Id": 6024,
            "ServerRedirectedEmbedUri": null,
            "ServerRedirectedEmbedUrl": "",
            "Title": "Test Item",
            "Text": null,
            "Integer": 23,
            "ContentTypeId": "0x01008DBF3136F91A674284F05535CB9FAB51",
            "ComplianceAssetId": null,
            "Note": null,
            "Datetime": null,
            "Choice": "Choice 1",
            "MultiChoice": null,
            "Boolean": true,
            "Number": 90,
            "Currency": null,
            "URL": null,
            "UserId": null,
            "UserStringId": null,
            "MultiPersonId": null,
            "MultiPersonStringId": null,
            "AverageRating": null,
            "RatingCount": null,
            "RatedByStringId": null,
            "LikesCount": null,
            "LikedByStringId": null,
            "Site_x0020_URL": "https://bluesidenl.sharepoint.com/sites/dev/dashboard/subsite-test/",
            "Site_x0020_title": null,
            "ID": 6024,
            "Modified": "2018-01-03T12:41:18Z",
            "Created": "2017-11-24T09:09:21Z",
            "AuthorId": 9,
            "EditorId": 9,
            "OData__UIVersionString": "1.0",
            "Attachments": false,
            "GUID": "6d122481-af56-40e3-a677-53dd27bd0950"
        },
            {
            "odata.type": "SP.Data.TestlistListItem",
            "odata.id": "e3961d56-b094-4eb3-b6c8-7a72aac40757",
            "odata.etag": "\"11\"",
            "odata.editLink": "Web/Lists(guid'3f891819-5635-47ff-81c1-992754c7859d')/Items(6025)",
            "FileSystemObjectType": 0,
            "Id": 6025,
            "ServerRedirectedEmbedUri": null,
            "ServerRedirectedEmbedUrl": "",
            "Title": "webhook test",
            "Text": null,
            "Integer": 33,
            "ContentTypeId": "0x01008DBF3136F91A674284F05535CB9FAB51",
            "ComplianceAssetId": null,
            "Note": null,
            "Datetime": null,
            "Choice": "Choice 1",
            "MultiChoice": [
                "Choice 1",
                "Choice 2"
            ],
            "Boolean": true,
            "Number": 50,
            "Currency": null,
            "URL": null,
            "UserId": null,
            "UserStringId": null,
            "MultiPersonId": null,
            "MultiPersonStringId": null,
            "AverageRating": null,
            "RatingCount": null,
            "RatedByStringId": null,
            "LikesCount": null,
            "LikedByStringId": null,
            "Site_x0020_URL": null,
            "Site_x0020_title": null,
            "ID": 6025,
            "Modified": "2018-01-03T14:31:37Z",
            "Created": "2017-12-01T18:11:34Z",
            "AuthorId": 9,
            "EditorId": 9,
            "OData__UIVersionString": "3.0",
            "Attachments": false,
            "GUID": "cc7ee228-5290-434b-aba8-94f308117f92"
        },
            {
            "odata.type": "SP.Data.TestlistListItem",
            "odata.id": "becb18fc-6dfe-4546-854b-c89ed06e2469",
            "odata.etag": "\"26\"",
            "odata.editLink": "Web/Lists(guid'3f891819-5635-47ff-81c1-992754c7859d')/Items(6027)",
            "FileSystemObjectType": 0,
            "Id": 6027,
            "ServerRedirectedEmbedUri": null,
            "ServerRedirectedEmbedUrl": "",
            "Title": "asdf",
            "Text": null,
            "Integer": 3,
            "ContentTypeId": "0x01008DBF3136F91A674284F05535CB9FAB51",
            "ComplianceAssetId": null,
            "Note": null,
            "Datetime": null,
            "Choice": "Choice 1",
            "MultiChoice": [
                "Choice 1"
            ],
            "Boolean": true,
            "Number": 80,
            "Currency": null,
            "URL": null,
            "UserId": null,
            "UserStringId": null,
            "MultiPersonId": null,
            "MultiPersonStringId": null,
            "AverageRating": null,
            "RatingCount": null,
            "RatedByStringId": null,
            "LikesCount": null,
            "LikedByStringId": null,
            "Site_x0020_URL": null,
            "Site_x0020_title": null,
            "ID": 6027,
            "Modified": "2018-01-03T16:13:30Z",
            "Created": "2017-12-13T17:41:32Z",
            "AuthorId": 9,
            "EditorId": 9,
            "OData__UIVersionString": "24.0",
            "Attachments": false,
            "GUID": "9a39dcfe-a36b-4f49-952e-ab4b54ddf8a6"
        },
            {
            "odata.type": "SP.Data.TestlistListItem",
            "odata.id": "c7d666f3-92af-4228-b76c-6307a27eed7b",
            "odata.etag": "\"1\"",
            "odata.editLink": "Web/Lists(guid'3f891819-5635-47ff-81c1-992754c7859d')/Items(6028)",
            "FileSystemObjectType": 0,
            "Id": 6028,
            "ServerRedirectedEmbedUri": null,
            "ServerRedirectedEmbedUrl": "",
            "Title": "Subsite test",
            "Text": null,
            "Integer": 25,
            "ContentTypeId": "0x01008DBF3136F91A674284F05535CB9FAB51",
            "ComplianceAssetId": null,
            "Note": null,
            "Datetime": null,
            "Choice": "Choice 1",
            "MultiChoice": null,
            "Boolean": true,
            "Number": null,
            "Currency": null,
            "URL": null,
            "UserId": null,
            "UserStringId": null,
            "MultiPersonId": null,
            "MultiPersonStringId": null,
            "AverageRating": null,
            "RatingCount": null,
            "RatedByStringId": null,
            "LikesCount": null,
            "LikedByStringId": null,
            "Site_x0020_URL": "https://bluesidenl.sharepoint.com/sites/dev/dashboard/subsite-test/",
            "Site_x0020_title": null,
            "ID": 6028,
            "Modified": "2018-01-18T12:40:00Z",
            "Created": "2018-01-18T12:40:00Z",
            "AuthorId": 9,
            "EditorId": 9,
            "OData__UIVersionString": "1.0",
            "Attachments": false,
            "GUID": "e2d532ef-db10-4d68-b9a4-4cc4761eeef3"
        },
            {
            "odata.type": "SP.Data.TestlistListItem",
            "odata.id": "7c44f273-e66a-4358-be99-eff14a9cdd86",
            "odata.etag": "\"1\"",
            "odata.editLink": "Web/Lists(guid'3f891819-5635-47ff-81c1-992754c7859d')/Items(6029)",
            "FileSystemObjectType": 0,
            "Id": 6029,
            "ServerRedirectedEmbedUri": null,
            "ServerRedirectedEmbedUrl": "",
            "Title": "Subsite test",
            "Text": null,
            "Integer": 25,
            "ContentTypeId": "0x01008DBF3136F91A674284F05535CB9FAB51",
            "ComplianceAssetId": null,
            "Note": null,
            "Datetime": null,
            "Choice": "Choice 1",
            "MultiChoice": null,
            "Boolean": true,
            "Number": null,
            "Currency": null,
            "URL": null,
            "UserId": null,
            "UserStringId": null,
            "MultiPersonId": null,
            "MultiPersonStringId": null,
            "AverageRating": null,
            "RatingCount": null,
            "RatedByStringId": null,
            "LikesCount": null,
            "LikedByStringId": null,
            "Site_x0020_URL": "https://bluesidenl.sharepoint.com/sites/dev/dashboard/subsite-test/",
            "Site_x0020_title": null,
            "ID": 6029,
            "Modified": "2018-01-18T12:40:30Z",
            "Created": "2018-01-18T12:40:30Z",
            "AuthorId": 9,
            "EditorId": 9,
            "OData__UIVersionString": "1.0",
            "Attachments": false,
            "GUID": "c77d3c9f-9216-4c2e-9032-18afc8f08dab"
        }
        ]
    };
    
    constructor() { }

    getList(listTitle: string): Observable<any> {
        return new Observable((observer) => {
            observer.next(this.mockList);
            observer.complete();
        });
    }

    getToken(): any {
        return "";
    }


}
